global:
  scrape_interval:     30s
  evaluation_interval: 30s

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    relabel_configs:
      - replacement: localhost
        target_label: server
  
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    relabel_configs:
      - replacement: localhost
        target_label: server
  
  - job_name: 'smart-exporter'
    static_configs:
      - targets: ['smart-exporter:8080']
    relabel_configs:
      - replacement: localhost
        target_label: server