{
 "title": "NAS",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "server", "query": "localhost" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode=\"system\",server=~'$server'}[5m]))",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='user',server=~'$server'}[5m]))",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='iowait',server=~'$server'}[5m]))",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{server=~'$server',mode!='idle'}[5m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='nice',server=~'$server'}[5m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{server=~\"$server\"}",
     "legendFormat": "1min"
    },
    {
     "expr": "node_load5{server=~\"$server\"}",
     "legendFormat": "5min"
    },
    {
     "expr": "node_load15{server=~\"$server\"}",
     "legendFormat": "15min"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{server=~'$server'} - node_memory_MemFree_bytes{server=~'$server'} - node_memory_Buffers_bytes{server=~'$server'} - node_memory_Cached_bytes{server=~'$server'}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemTotal_bytes{server=~'$server'}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_memory_SwapTotal_bytes{server=~'$server'} - node_memory_SwapFree_bytes{server=~'$server'}",
     "legendFormat": "Swap Used"
    }
   ]
  },
  {
   "title": "Temp",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{server=~\"$server\",chip!=\"battery\"}",
     "legendFormat": "{{ sensor }}"
    },
    {
     "expr": "smart_parameter{server=~\"$server\", id=\"194\"}",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  { "title": "HDD", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Temperture_Gauge",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "smart_parameter{server=~\"$server\", id=\"194\"}",
     "legendFormat": "{{ disk }}"
    }
   ]
  },
  {
   "title": "Temperature_Graph",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 9, "y": 16 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "smart_parameter{server=~\"$server\", id=\"194\"}",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "Active devices",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(hdparm_drive_state_active >= 0)"
    }
   ]
  },
  {
   "title": "Unhealthy Disks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(smart_healthy)-sum(smart_healthy)"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 19 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(smart_parameter{critical=\"true\"})"
    }
   ]
  },
  {
   "title": "Smart criticals",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "smart_parameter{critical=\"true\",server=\"$server\"}"
    }
   ]
  },
  {
   "title": "Disk State",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 5, "w": 11, "x": 8, "y": 22 },
   "targets": [
    {
     "expr": "hdparm_drive_state_active{server=\"$server\"}",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "Power-on Hours",
   "type": "bargauge",
   "description": "WD Red PoH Limit: 1.000.000  \nWD Green PoH Limit: Unlisted",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 22 },
   "targets": [
    {
     "expr": "smart_parameter{id=\"9\",server=\"$server\"}",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "table",
   "gridPos": { "h": 5, "w": 11, "x": 8, "y": 27 },
   "targets": [
    {
     "expr": "smart_parameter{id=\"194\",server=\"$server\"}",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "LCC",
   "type": "bargauge",
   "description": "WD Red LCC Limit: 600.000  \nWD Blue/Green  LCC Limit: 300.000",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 27 },
   "targets": [
    {
     "expr": "smart_parameter{id=\"193\",server=\"$server\"}",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "LCC per 24h",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(increase(smart_parameter{id=\"193\",server=\"$server\"}[24h]))",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100.0 - 100 * (node_filesystem_avail_bytes{server='$server',device !~'tmpfs',device!~'by-uuid',mountpoint!~'/var/.*',mountpoint!~'/sharedfolders/.*',mountpoint!~'/export/.*'} / node_filesystem_size_bytes{server=~'$server',device !~'tmpfs',device!~'by-uuid'})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Disk IOs per Device",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short", "label": "IO/second read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{server=~'$server',device=~'sd.'}[5m]) or irate(node_disk_reads_completed{server=~'$server',device=~'sd.'}[5m])",
     "legendFormat": "{{device}}_read"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{server=~'$server',device=~'sd.'}[5m]) or irate(node_disk_writes_completed{server=~'$server',device=~'sd.'}[5m])",
     "legendFormat": "{{device}}_write"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "decbytes", "label": "bytes in (-) / bits out (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{server=~'$server',device=~\"eth.\"}[5m])*8 or irate(node_network_receive_bytes{server=~'$server',device=~\"eth.\"}[5m])*8",
     "legendFormat": "{{device}}_in"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{server=~'$server',device=~\"eth.\"}[5m])*8 or irate(node_network_transmit_bytes{server=~'$server',device=~\"eth.\"}[5m])*8",
     "legendFormat": "{{device}}_out"
    }
   ]
  },
  {
   "title": "Disk Utilization per Device",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{server=~\"$server\", device=~\"...\"}[5m])*100 or irate(node_disk_io_time_ms{server=~\"$server\",device=~\"...\"}[5m])/10",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk Throughput per Device",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    {
     "format": "decbytes",
     "label": "Bytes/second read (-) / write (+)"
    }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{server=~'$server', device=~\"sd.\"}[5m]) * 512",
     "legendFormat": "{{device}}_read"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{server=~'$server',  device=~\"sd.\"}[5m]) * 512",
     "legendFormat": "{{device}}_write"
    }
   ]
  }
 ]
}